# Generated by Django 4.2.7 on 2023-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_size', models.IntegerField()),
                ('take_profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stop_loss_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
